master:
  build: jenkins-master
  volumes:
      - /var/log/jenkins:/var/log/jenkins
      - /var/jenkins_home:/var/jenkins_home
  ports:
    - "50000:50000"
  
nginx:
  build: jenkins-nginx
  ports:
    - "80:80"
  links:
    - master:jenkins-master