version: "3"
services:
  master:
    image: jenkins_master
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.8"
          memory: 1800M
      placement:
        constraints: [node.role == manager]
    volumes:
      - /var/log/jenkins:/var/log/jenkins
      - /var/jenkins_home:/var/jenkins_home
    ports:
      - "50000:50000"
    networks:
      webnet:
        aliases:
          - jenkins-master
  nginx:
    image: jenkins_nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  webnet:
