---

- hosts: all
  sudo: yes
  roles:
    - { role: jgeusebroek.docker,
        docker_opts: "-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375"
      }
    - franklinkim.docker-compose
  vars:
    docker_compose_version: 1.15.0
  tags: ["docker"]
  tasks:
    - name: Add the user 'ubuntu' to the group 'docker'
      user: name=ubuntu shell=/bin/bash groups=docker append=yes

    - name: Clean private key files path
      file:
        state: absent
        path: /vagrant/jenkins-slave/files/

    - name: Create private key files path 
      file:
        path: /vagrant/jenkins-slave/files/
        state: directory
        mode: 0755

    - name: Generate SSH keys
      shell: ssh-keygen -t rsa -b 4096 -f /vagrant/jenkins-slave/files/id_rsa -q -N ""
      args:
        creates: /vagrant/jenkins-slave/files/id_rsa

    - name: Rename id_rsa.pub
      command: mv /vagrant/jenkins-slave/files/id_rsa.pub /vagrant/jenkins-slave/files/authorized_keys

    - name: Init the host as a swarm manager
      command: docker swarm init

    - name: Build Jenkins master docker-compose file
      command: docker-compose -p jenkins -f docker-compose-master.yml build
      args:
        chdir: /vagrant

    - name: Build Jenkins slave docker-compose file
      command: docker-compose -p jenkins -f docker-compose-slave.yml build
      args:
        chdir: /vagrant

    - meta: flush_handlers

    - name: Add 
      command: sudo chown 1000 /var/log/jenkins

    - name: Add 
      command: sudo chown 1000 /var/jenkins_home  

    - name: Run Docker stack deploy file
      command: docker stack deploy -c docker-stack.yml jenkins-swarm
      args:
        chdir: /vagrant